### ISSUE TITLE
How to import or how to use this pulgin in my flutter project

### ISSUE THREAD

**Issue by arpandesai** [kangshaojun/flutter-incall-manager#2]
I am a newbie to Flutter So 
can you tell me How I am supposed to import this plugin to Flutter project 

Thanks

**Comment by JasonHao123** [comment]
the same question, why not upload to pub.dev? Then it will be easy to use.

**Comment by GioviQ** [comment]
Try read https://flutter.dev/docs/development/packages-and-plugins/using-packages#dependencies-on-unpublished-packages

**Comment by GioviQ** [comment]
You can see how I used this plugin here https://github.com/GioviQ/video-chat-experiment

**Comment by CoreyCole** [comment]
If anyone is still confused, you add to your pubspec.yaml dependencies:

```yaml
dependencies:
  # ...
  flutter_incall_manager:
    git:
      url: git://github.com/kangshaojun/flutter-incall-manager.git
```

**Comment by pulstar** [comment]
The git URL above is not working when I did try to get the incall_manager package, so I checked the link right above and found the configuration below, that worked for me:

```yaml
  flutter_incall_manager:
    git:
      url: git://github.com/GioviQ/flutter-incall-manager.git
```
